In [39]:
import pandas as pd
import plotly.express as px

In [40]:
x_df = pd.read_csv("data/engieX.csv", header=0, sep=";")
y_df = pd.read_csv("data/engieY.csv", header=0, sep=";")

In [41]:
x_wt1_df = x_df[x_df['MAC_CODE']=='WT1'].copy()
x_wt1_df

,ID,MAC_CODE,Date_time,Pitch_angle,Pitch_angle_min,Pitch_angle_max,Pitch_angle_std,Hub_temperature,Hub_temperature_min,Hub_temperature_max,...,Rotor_speed,Rotor_speed_min,Rotor_speed_max,Rotor_speed_std,Rotor_bearing_temperature,Rotor_bearing_temperature_min,Rotor_bearing_temperature_max,Rotor_bearing_temperature_std,Absolute_wind_direction_c,Nacelle_angle_c
462679,462680,WT1,1.0,92.410004,92.410004,92.410004,0.00,8.24,8.000000,9.0,...,0.000000,0.00,0.000000,0.00,2.380000,2.300000,2.500000,0.06,301.44000,302.89999
462680,462681,WT1,2.0,92.410004,92.410004,92.410004,0.00,8.19,8.000000,9.0,...,0.000000,0.00,0.000000,0.00,2.420000,2.300000,2.500000,0.07,299.73999,302.89999
462681,462682,WT1,3.0,92.410004,92.410004,92.410004,0.00,8.90,8.000000,9.0,...,0.000000,0.00,0.000000,0.00,2.420000,2.300000,2.500000,0.07,332.13000,302.89999
462682,462683,WT1,4.0,92.410004,92.410004,92.410004,0.00,7.62,8.000000,9.0,...,0.000000,0.00,0.000000,0.00,2.400000,2.300000,2.500000,0.07,322.01999,302.89999
462683,462684,WT1,5.0,92.410004,92.410004,92.410004,0.00,7.09,7.000000,8.0,...,0.000000,0.00,0.000000,0.00,2.410000,2.300000,2.500000,0.07,322.75000,302.89999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617381,617382,WT1,157676.0,-1.010000,-1.010000,-0.840000,0.01,18.00,17.090000,18.0,...,16.930000,14.79,17.379999,0.52,35.790001,35.700001,35.900002,0.02,229.27000,231.56000
617382,617383,WT1,157677.0,-1.010000,-1.010000,-1.010000,0.00,17.99,17.469999,18.0,...,16.969999,15.39,17.389999,0.34,35.810001,35.599998,35.849998,0.06,227.53000,231.56000
617383,617384,WT1,157678.0,-0.810000,-1.010000,1.490000,0.58,18.00,17.770000,18.0,...,17.040001,15.67,17.420000,0.30,36.060001,35.799999,36.099998,0.10,228.75000,231.56000
617384,617385,WT1,157679.0,-1.000000,-1.010000,-0.620000,0.03,18.00,17.700001,18.0,...,16.860001,14.86,17.340000,0.60,36.189999,36.099998,36.200001,0.05,226.16000,231.56000
617385,617386,WT1,157680.0,-0.910000,-1.010000,1.080000,0.42,18.00,18.000000,18.0,...,17.100000,16.17,17.389999,0.15,36.240002,36.200001,36.400002,0.06,226.06000,231.56000

In [42]:
y_wt1_df=y_df[y_df.ID.isin(x_wt1_df.ID)].copy()
y_wt1_df

            ID      TARGET
462679  462680    -2.72700
462680  462681    -2.78200
462681  462682    -2.83700
462682  462683    -2.55100
462683  462684    -3.18900
...        ...         ...
617381  617382  1151.82200
617382  617383  1119.93300
617383  617384  1223.82800
617384  617385  1086.55900
617385  617386  1142.92311

[154707 rows x 2 columns]

In [43]:
y_wt1_df.isna().sum()

ID        0
TARGET    0
dtype: int64

In [44]:
# px.scatter(x=x_df.Generator_speed,y=y_df.TARGET,color=x_df.MAC_CODE)

In [45]:
# px.scatter(x=x_df.Generator_converter_speed,y=y_df.TARGET,color=x_df.MAC_CODE)

In [46]:
# px.scatter(x=x_wt1_df.Absolute_wind_direction,y=x_wt1_df.Absolute_wind_direction_c)

In [47]:
df=x_wt1_df.merge(y_wt1_df, how="left", on = "ID")
df

,ID,MAC_CODE,Date_time,Pitch_angle,Pitch_angle_min,Pitch_angle_max,Pitch_angle_std,Hub_temperature,Hub_temperature_min,Hub_temperature_max,...,Rotor_speed_min,Rotor_speed_max,Rotor_speed_std,Rotor_bearing_temperature,Rotor_bearing_temperature_min,Rotor_bearing_temperature_max,Rotor_bearing_temperature_std,Absolute_wind_direction_c,Nacelle_angle_c,TARGET
0,462680,WT1,1.0,92.410004,92.410004,92.410004,0.00,8.24,8.000000,9.0,...,0.00,0.000000,0.00,2.380000,2.300000,2.500000,0.06,301.44000,302.89999,-2.72700
1,462681,WT1,2.0,92.410004,92.410004,92.410004,0.00,8.19,8.000000,9.0,...,0.00,0.000000,0.00,2.420000,2.300000,2.500000,0.07,299.73999,302.89999,-2.78200
2,462682,WT1,3.0,92.410004,92.410004,92.410004,0.00,8.90,8.000000,9.0,...,0.00,0.000000,0.00,2.420000,2.300000,2.500000,0.07,332.13000,302.89999,-2.83700
3,462683,WT1,4.0,92.410004,92.410004,92.410004,0.00,7.62,8.000000,9.0,...,0.00,0.000000,0.00,2.400000,2.300000,2.500000,0.07,322.01999,302.89999,-2.55100
4,462684,WT1,5.0,92.410004,92.410004,92.410004,0.00,7.09,7.000000,8.0,...,0.00,0.000000,0.00,2.410000,2.300000,2.500000,0.07,322.75000,302.89999,-3.18900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154702,617382,WT1,157676.0,-1.010000,-1.010000,-0.840000,0.01,18.00,17.090000,18.0,...,14.79,17.379999,0.52,35.790001,35.700001,35.900002,0.02,229.27000,231.56000,1151.82200
154703,617383,WT1,157677.0,-1.010000,-1.010000,-1.010000,0.00,17.99,17.469999,18.0,...,15.39,17.389999,0.34,35.810001,35.599998,35.849998,0.06,227.53000,231.56000,1119.93300
154704,617384,WT1,157678.0,-0.810000,-1.010000,1.490000,0.58,18.00,17.770000,18.0,...,15.67,17.420000,0.30,36.060001,35.799999,36.099998,0.10,228.75000,231.56000,1223.82800
154705,617385,WT1,157679.0,-1.000000,-1.010000,-0.620000,0.03,18.00,17.700001,18.0,...,14.86,17.340000,0.60,36.189999,36.099998,36.200001,0.05,226.16000,231.56000,1086.55900
154706,617386,WT1,157680.0,-0.910000,-1.010000,1.080000,0.42,18.00,18.000000,18.0,...,16.17,17.389999,0.15,36.240002,36.200001,36.400002,0.06,226.06000,231.56000,1142.92311

In [48]:
for col in df.columns:
    n_na = df[col].isna().sum()
    if n_na > 0:
        print(f"{col}: {n_na} missing values ({n_na/len(df)*100:.2f}%)")

Generator_converter_speed: 2016 missing values (1.30%)
Generator_converter_speed_min: 2016 missing values (1.30%)
Generator_converter_speed_max: 2016 missing values (1.30%)
Generator_converter_speed_std: 2016 missing values (1.30%)
Gearbox_inlet_temperature: 2016 missing values (1.30%)
Gearbox_inlet_temperature_min: 2016 missing values (1.30%)
Gearbox_inlet_temperature_max: 2016 missing values (1.30%)
Gearbox_inlet_temperature_std: 2016 missing values (1.30%)
Grid_voltage: 29699 missing values (19.20%)
Grid_voltage_min: 29699 missing values (19.20%)
Grid_voltage_max: 29699 missing values (19.20%)
Grid_voltage_std: 29699 missing values (19.20%)
Absolute_wind_direction_c: 18 missing values (0.01%)
Nacelle_angle_c: 18 missing values (0.01%)

In [49]:
df.loc[df.Absolute_wind_direction_c.isna(),'Absolute_wind_direction_c']=df[df.Absolute_wind_direction_c.isna()].Absolute_wind_direction
df.loc[df.Nacelle_angle_c.isna(),'Nacelle_angle_c']=df[df.Nacelle_angle_c.isna()].Nacelle_angle
df.isna().sum()

ID                               0
MAC_CODE                         0
Date_time                        0
Pitch_angle                      0
Pitch_angle_min                  0
                                ..
Rotor_bearing_temperature_max    0
Rotor_bearing_temperature_std    0
Absolute_wind_direction_c        0
Nacelle_angle_c                  0
TARGET                           0
Length: 79, dtype: int64

In [50]:
# display max of columns with _std suffix
for col in df.columns:
    if col.endswith('_std'):
        print(f"{col}: max={df[col].max()}, min={df[col].min()}")

Pitch_angle_std: max=94.769997, min=0.0
Hub_temperature_std: max=0.83999997, min=0.0
Generator_converter_speed_std: max=880.54999, min=0.0
Generator_speed_std: max=873.71997, min=0.0
Generator_bearing_1_temperature_std: max=3.4400001, min=0.0
Generator_bearing_2_temperature_std: max=3.3499999, min=0.0
Generator_stator_temperature_std: max=3.5999999, min=0.0
Gearbox_bearing_1_temperature_std: max=9.71, min=0.0
Gearbox_bearing_2_temperature_std: max=8.8999996, min=0.0
Gearbox_inlet_temperature_std: max=9.5799999, min=0.0
Gearbox_oil_sump_temperature_std: max=3.6400001, min=0.0
Nacelle_angle_std: max=178.13, min=0.0
Nacelle_temperature_std: max=4.1199999, min=0.0
Outdoor_temperature_std: max=3.1300001, min=0.0
Grid_frequency_std: max=25.02, min=0.0
Grid_voltage_std: max=370.98999, min=0.0
Rotor_speed_std: max=8.3000002, min=0.0
Rotor_bearing_temperature_std: max=3.3199999, min=0.0

La plupart des std sont faibles, on vire les colonnes min max et std

In [51]:
df.drop(columns=['MAC_CODE','Absolute_wind_direction','Nacelle_angle']+[col for col in df.columns if col.endswith(('_min','_max','_std'))],inplace=True)

df

,ID,Date_time,Pitch_angle,Hub_temperature,Generator_converter_speed,Generator_speed,Generator_bearing_1_temperature,Generator_bearing_2_temperature,Generator_stator_temperature,Gearbox_bearing_1_temperature,...,Gearbox_oil_sump_temperature,Nacelle_temperature,Outdoor_temperature,Grid_frequency,Grid_voltage,Rotor_speed,Rotor_bearing_temperature,Absolute_wind_direction_c,Nacelle_angle_c,TARGET
0,462680,1.0,92.410004,8.24,3.92,0.17,7.700000,6.840000,4.900000,2.390000,...,2.100000,4.890000,-0.70,49.980000,684.19000,0.000000,2.380000,301.44000,302.89999,-2.72700
1,462681,2.0,92.410004,8.19,3.83,0.01,7.710000,6.880000,4.900000,2.390000,...,2.100000,4.730000,-0.62,49.959999,686.10999,0.000000,2.420000,299.73999,302.89999,-2.78200
2,462682,3.0,92.410004,8.90,3.92,0.13,7.700000,6.890000,4.890000,2.370000,...,2.100000,4.540000,-0.60,49.959999,688.29999,0.000000,2.420000,332.13000,302.89999,-2.83700
3,462683,4.0,92.410004,7.62,4.49,0.55,7.700000,6.900000,4.890000,2.350000,...,2.100000,4.330000,-0.60,49.980000,690.08002,0.000000,2.400000,322.01999,302.89999,-2.55100
4,462684,5.0,92.410004,7.09,4.48,0.55,7.700000,6.900000,4.890000,2.330000,...,2.130000,4.220000,-0.60,49.980000,689.97998,0.000000,2.410000,322.75000,302.89999,-3.18900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154702,617382,157676.0,-1.010000,18.00,1776.02,1778.25,38.340000,39.369999,61.439999,63.160000,...,55.830002,18.570000,10.45,49.970001,696.40997,16.930000,35.790001,229.27000,231.56000,1151.82200
154703,617383,157677.0,-1.010000,17.99,1779.74,1782.00,36.380001,38.250000,59.770000,63.700001,...,55.259998,19.680000,10.46,50.000000,697.21002,16.969999,35.810001,227.53000,231.56000,1119.93300
154704,617384,157678.0,-0.810000,18.00,1787.21,1789.47,37.709999,38.080002,61.500000,65.809998,...,55.779999,22.740000,10.60,50.000000,696.76001,17.040001,36.060001,228.75000,231.56000,1223.82800
154705,617385,157679.0,-1.000000,18.00,1768.89,1771.10,39.950001,38.490002,62.639999,65.360001,...,55.680000,24.080000,10.60,50.000000,694.56000,16.860001,36.189999,226.16000,231.56000,1086.55900
154706,617386,157680.0,-0.910000,18.00,1793.12,1795.36,41.840000,39.090000,64.910004,65.760002,...,55.869999,23.610001,10.60,50.009998,694.13000,17.100000,36.240002,226.06000,231.56000,1142.92311

on ne garde que les valeurs par heure

In [52]:
df = df[df.Date_time % 6 == 1].copy()
df

,ID,Date_time,Pitch_angle,Hub_temperature,Generator_converter_speed,Generator_speed,Generator_bearing_1_temperature,Generator_bearing_2_temperature,Generator_stator_temperature,Gearbox_bearing_1_temperature,...,Gearbox_oil_sump_temperature,Nacelle_temperature,Outdoor_temperature,Grid_frequency,Grid_voltage,Rotor_speed,Rotor_bearing_temperature,Absolute_wind_direction_c,Nacelle_angle_c,TARGET
0,462680,1.0,92.410004,8.240000,3.92,0.1700,7.700000,6.840000,4.900000,2.390000,...,2.100000,4.890000,-0.70,49.980000,684.19000,0.000000,2.380000,301.440000,302.899990,-2.727000
6,462686,7.0,92.410004,6.830000,3.93,0.1700,7.700000,6.850000,4.780000,2.300000,...,2.110000,4.840000,-0.74,0.000000,0.00000,0.000000,2.320000,303.250000,302.899990,0.100000
16,462696,673.0,92.410004,2.000000,4.26,0.0000,-1.690000,-2.640000,-2.600000,-1.900000,...,1.750000,2.010000,-3.40,50.000000,688.29999,0.000000,-2.100000,84.379997,301.810000,-4.993000
22,462702,679.0,92.410004,3.960000,4.09,0.0600,-0.230000,-1.350000,-2.480000,-1.700000,...,0.840000,2.180000,-3.74,49.959999,686.22998,0.000000,-2.080000,76.830002,79.000000,-4.542000
28,462708,685.0,92.410004,4.000000,4.46,0.4300,0.750000,-0.500000,-2.280000,-1.600000,...,0.170000,2.200000,-4.00,49.990002,684.65002,0.000000,-2.020000,59.270000,69.120003,-3.145000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154677,617357,157651.0,-1.000000,18.000000,1792.59,1794.8400,32.400002,36.439999,59.680000,71.739998,...,52.220001,19.240000,10.20,50.020000,698.78998,17.090000,35.730000,239.500000,239.250000,1230.637000
154683,617363,157657.0,-1.000000,17.760000,1776.84,1779.0601,36.270000,37.509998,59.470001,70.470001,...,51.360001,20.020000,10.38,50.000000,699.76001,16.940001,35.750000,234.899990,239.250000,1057.122989
154689,617369,157663.0,-1.000000,17.510000,1767.27,1769.4900,40.720001,40.349998,63.099998,69.209999,...,56.939999,19.469999,10.41,50.000000,698.97998,16.850000,35.599998,230.570010,227.170000,998.240022
154695,617375,157669.0,-1.000000,17.549999,1775.65,1777.9100,42.040001,40.750000,63.630001,62.869999,...,55.990002,20.170000,10.51,50.029999,701.15997,16.930000,35.709999,224.090000,237.970000,1066.154011
154701,617381,157675.0,-1.000000,18.000000,1787.27,1789.5200,41.360001,40.570000,63.810001,64.970001,...,57.080002,20.480000,10.45,50.009998,696.65002,17.040001,35.889999,231.590000,231.560000,1147.015000

In [53]:
for col in df.columns:
    n_na = df[col].isna().sum()
    if n_na > 0:
        print(f"{col}: {n_na} missing values ({n_na/len(df)*100:.2f}%)")

Generator_converter_speed: 336 missing values (1.30%)
Gearbox_inlet_temperature: 336 missing values (1.30%)
Grid_voltage: 4949 missing values (19.21%)

méthode bourrin pour le datacamp

In [54]:
df.drop(columns=['ID','Date_time','Generator_converter_speed','Gearbox_inlet_temperature','Grid_voltage'],inplace=True)
df

,Pitch_angle,Hub_temperature,Generator_speed,Generator_bearing_1_temperature,Generator_bearing_2_temperature,Generator_stator_temperature,Gearbox_bearing_1_temperature,Gearbox_bearing_2_temperature,Gearbox_oil_sump_temperature,Nacelle_temperature,Outdoor_temperature,Grid_frequency,Rotor_speed,Rotor_bearing_temperature,Absolute_wind_direction_c,Nacelle_angle_c,TARGET
0,92.410004,8.240000,0.1700,7.700000,6.840000,4.900000,2.390000,2.420000,2.100000,4.890000,-0.70,49.980000,0.000000,2.380000,301.440000,302.899990,-2.727000
6,92.410004,6.830000,0.1700,7.700000,6.850000,4.780000,2.300000,2.330000,2.110000,4.840000,-0.74,0.000000,0.000000,2.320000,303.250000,302.899990,0.100000
16,92.410004,2.000000,0.0000,-1.690000,-2.640000,-2.600000,-1.900000,-1.300000,1.750000,2.010000,-3.40,50.000000,0.000000,-2.100000,84.379997,301.810000,-4.993000
22,92.410004,3.960000,0.0600,-0.230000,-1.350000,-2.480000,-1.700000,-1.200000,0.840000,2.180000,-3.74,49.959999,0.000000,-2.080000,76.830002,79.000000,-4.542000
28,92.410004,4.000000,0.4300,0.750000,-0.500000,-2.280000,-1.600000,-1.010000,0.170000,2.200000,-4.00,49.990002,0.000000,-2.020000,59.270000,69.120003,-3.145000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154677,-1.000000,18.000000,1794.8400,32.400002,36.439999,59.680000,71.739998,72.290001,52.220001,19.240000,10.20,50.020000,17.090000,35.730000,239.500000,239.250000,1230.637000
154683,-1.000000,17.760000,1779.0601,36.270000,37.509998,59.470001,70.470001,71.230003,51.360001,20.020000,10.38,50.000000,16.940001,35.750000,234.899990,239.250000,1057.122989
154689,-1.000000,17.510000,1769.4900,40.720001,40.349998,63.099998,69.209999,71.980003,56.939999,19.469999,10.41,50.000000,16.850000,35.599998,230.570010,227.170000,998.240022
154695,-1.000000,17.549999,1777.9100,42.040001,40.750000,63.630001,62.869999,71.040001,55.990002,20.170000,10.51,50.029999,16.930000,35.709999,224.090000,237.970000,1066.154011
154701,-1.000000,18.000000,1789.5200,41.360001,40.570000,63.810001,64.970001,72.110001,57.080002,20.480000,10.45,50.009998,17.040001,35.889999,231.590000,231.560000,1147.015000

# ML

In [55]:
from sklearn.linear_model import RidgeCV, ElasticNetCV, LassoCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

## Séparation des données

In [56]:
# keep 20% for test
# on a des données temporelles, donc on garde les 20% dernières lignes pour test
df.reset_index(drop=True,inplace=True)
cv_thres = 0.8 * len(df)
train_df = df.iloc[:int(cv_thres)].copy()
test_df = df.iloc[int(cv_thres):].copy()

In [73]:
from sklearn.metrics import mean_absolute_error

X=train_df.drop(["TARGET"], axis=1)
y=train_df["TARGET"]

X_test=test_df.drop(["TARGET"], axis=1)
y_test=test_df["TARGET"]

# Régression linéaire (MCO)
simple_reg = LinearRegression().fit(X, y)
#MAE d'entrainement
train_mae=mean_absolute_error(simple_reg.predict(X),y)
print(f"MAE d'entraînement : {train_mae}")
#MAE de test
test_mae=mean_absolute_error(simple_reg.predict(X_test),y_test)
print(f"MAE de test : {test_mae}")

MAE d'entraînement : 102.26921145058104
MAE de test : 109.64571055232912

In [ ]:
# Initialisation de KFold
kf = KFold(n_splits=5, shuffle=True, random_state=0)

# Création d'un dataframe pour comparer les résultats de chaque méthode (n blocs)
PREV = pd.DataFrame(
    {
        "Y": train_df["TARGET"]
    }
)

for i, (train_index, test_index) in enumerate(kf.split(train_df)):

    # Séparation des données en train et test
    X_train = train_df.iloc[train_index].drop(["TARGET"], axis=1)
    X_test = train_df.iloc[test_index].drop(["TARGET"], axis=1)
    Y_train = train_df.iloc[train_index]["TARGET"]

    # Mise à jour de la colonne 'bloc' dans PREV
    PREV.loc[test_index, "bloc"] = i

    # Régression linéaire (MCO)
    reg = LinearRegression()
    reg.fit(X_train, Y_train)
    PREV.loc[test_index, "MCO"] = reg.predict(X_test)

    # Définition d'un nouveau kf pour la validation croisée de lambda
    kf_lambda = KFold(n_splits=10, shuffle=True, random_state=0)

    # Lasso avec validation croisée
    lassocv = LassoCV(cv=kf_lambda)
    pipelassocv = Pipeline(steps=[("cr", StandardScaler()), ("lassocv", lassocv)])
    pipelassocv.fit(X_train, Y_train)
    PREV.loc[test_index, "lasso"] = pipelassocv.predict(X_test)

    # Ridge avec validation croisée
    grilleridge = lassocv.alphas_ * 100
    ridgecv = RidgeCV(cv=kf_lambda, alphas=grilleridge)
    piperidgecv = Pipeline(steps=[("cr", StandardScaler()), ("ridgecv", ridgecv)])
    piperidgecv.fit(X_train, Y_train)
    PREV.loc[test_index, "ridge"] = piperidgecv.predict(X_test)

    # ElasticNet avec validation croisée
    grilleelas = lassocv.alphas_ * 2
    elasticcv = ElasticNetCV(cv=kf_lambda, alphas=grilleelas)
    pipeelasticcv = Pipeline(steps=[("cr", StandardScaler()), ("elasticcv", elasticcv)])
    pipeelasticcv.fit(X_train, Y_train)
    PREV.loc[test_index, "elas"] = pipeelasticcv.predict(X_test)

    # Arbre de décision
    arbre = DecisionTreeRegressor()
    arbre.fit(X_train, Y_train)
    PREV.loc[test_index, "arbre"] = arbre.predict(X_test)

    # Forêt aléatoire
    foret = RandomForestRegressor(n_estimators=100)
    foret.fit(X_train, Y_train)
    PREV.loc[test_index, "foret100"] = foret.predict(X_test)

    # Forêt aléatoire
    foret = RandomForestRegressor(n_estimators=500, max_features=0.3)
    foret.fit(X_train, Y_train)
    PREV.loc[test_index, "foret500"] = foret.predict(X_test)

In [ ]:
import matplotlib.pyplot as plt

# Création de la figure avec deux sous-graphiques
fig, ax = plt.subplots(1, 2, figsize=(15, 6))

# Sous-graphe 1 : Comparaison des prédictions des modèles
for col in ["MCO", "ridge", "lasso", "elas", "arbre", "foret100", "foret500"]:
    ax[0].scatter(PREV["Y"], PREV[col], label=col, alpha=0.6)

ax[0].plot(
    [PREV["Y"].min(), PREV["Y"].max()],
    [PREV["Y"].min(), PREV["Y"].max()],
    "k--",
    lw=2,
    label="Valeurs réelles",
)
ax[0].set_xlabel("Valeurs réelles (Y)")
ax[0].set_ylabel("Prédictions")
ax[0].set_title("Comparaison des prédictions des modèles")
ax[0].legend()

# Sous-graphe 2 : Tableau des erreurs
# Conversion des erreurs en DataFrame pour affichage
erreurs_df = erreurs.reset_index()
erreurs_df.columns = ["Modèle", "Erreur quadratique moyenne"]

# Création du tableau
ax[1].axis("tight")
ax[1].axis("off")
table = ax[1].table(
    cellText=erreurs_df.values,
    colLabels=erreurs_df.columns,
    cellLoc="center",
    loc="center",
)
table.auto_set_font_size(False)
table.set_fontsize(10)
table.auto_set_column_width(col=list(range(len(erreurs_df.columns))))

# Affichage de la figure
plt.tight_layout()
plt.show()